import test from 'node:test';
import assert from 'node:assert/strict';
import {createWorld,acceptContract,acquire,commitCrime,collectCasing,dispose,tick,search,collectItem,inspectScene,records,submitTest,arrestAssessment,attemptArrest,closeUnsolved,handle,question,fire,save,load,move,lineOfSight,BUILDINGS,PLACES, type World} from '../src/sim.ts';
function advance(w:World,seconds:number){for(let i=0;i<seconds*20;i++)tick(w,.05);}
function crime(how:'legal'|'stolen'='legal'){const w=createWorld();w.started=true;w.player={...PLACES.contract};acceptContract(w);w.player={...(how==='legal'?PLACES.pawn:PLACES.stolen)};acquire(w,how);w.player={...PLACES.target};commitCrime(w);return w;}
function collectScene(w:World){w.phase='detective';w.incidents[0].discovered=true;w.player={...PLACES.target};inspectScene(w,'01');collectItem(w,'01-C');}
function recover(w:World,where:'dumpster'|'river'|'burial'){w.player={...PLACES[where]};dispose(w,where);w.phase='detective';search(w,where);collectItem(w,'W-104');}
function lab(w:World){w.player={...PLACES.lab};records(w);for(const item of w.items.filter(i=>i.collected)){submitTest(w,item.id,'prints');submitTest(w,item.id,'ballistics');}advance(w,31);}
test('legal and stolen acquisition preserve stable identity and prior owner prints',()=>{for(const how of ['legal','stolen'] as const){const w=crime(how);assert.equal(w.items[0].id,'W-104');assert.deepEqual(w.items[0].prints,['leon','ellis']);assert.equal(w.purchase,how);assert.equal(w.items[0].holder,'ellis');}});
test('fictional crime emits stable ballistic scene objects, without exposing facts',()=>{const w=crime();assert.equal(w.incidents.length,1);assert.equal(w.items.length,3);assert.equal(new Set(w.items.map(i=>i.signature)).size,1);assert.equal(w.facts.length,0);assert.equal(w.items[1].incident,'01');assert.equal(w.items[1].holder,null);});
test('casing collection changes later available scene evidence',()=>{const w=crime();collectCasing(w);collectScene(w);assert.equal(w.items.find(i=>i.id==='01-C')!.holder,'ellis');assert.equal(w.items.filter(i=>i.collected).length,1);});
test('water uses configurable interval and preserves ballistic identity',()=>{const w=crime();w.settings.waterWashSeconds=12;w.player={...PLACES.river};dispose(w,'river');const gun=w.items[0];advance(w,2);assert.ok(gun.prints.includes('ellis'));advance(w,1.1);assert.deepEqual(gun.prints,[]);assert.equal(gun.signature,'BR-47');assert.equal(gun.history.filter(e=>e.action==='Water removed surface prints').length,1);});
test('retrieving from water stops later degradation of sealed evidence',()=>{const w=crime();w.settings.waterWashSeconds=20;recover(w,'river');advance(w,20);assert.ok(w.items[0].prints.includes('ellis'));assert.equal(w.items[0].submergedAt,undefined);});
test('burial conceals the same item until search and preserves traces',()=>{const w=crime();w.player={...PLACES.burial};dispose(w,'burial');w.phase='detective';collectItem(w,'W-104');assert.equal(w.items[0].collected,false);advance(w,100);search(w,'burial');collectItem(w,'W-104');assert.equal(w.items[0].collected,true);assert.deepEqual(w.items[0].prints,['leon','ellis']);});
test('NPC retrieves and reuses dumpster gun through movement and shared object system',()=>{const w=crime();w.player={...PLACES.dumpster};dispose(w,'dumpster');advance(w,200);const gun=w.items[0],mara=w.npcs.find(n=>n.id==='mara')!;assert.equal(mara.retrieved,true);assert.equal(mara.reused,true);assert.equal(w.items.filter(i=>i.kind==='pistol').length,1);assert.equal(w.incidents.length,2);assert.equal(gun.id,'W-104');assert.deepEqual(gun.prints,['leon','ellis','mara']);assert.equal(w.items.find(i=>i.id==='02-C')!.signature,gun.signature);assert.ok(gun.history.some(e=>e.action.includes('incident 01')));assert.ok(gun.history.some(e=>e.action.includes('incident 02')));});
test('early dumpster recovery prevents NPC reuse',()=>{const w=crime();recover(w,'dumpster');advance(w,200);assert.equal(w.incidents.length,1);assert.equal(w.npcs.find(n=>n.id==='mara')!.retrieved,false);});
test('witnesses require both range and unobstructed sight',()=>{const w=crime();assert.ok(w.npcs.find(n=>n.id==='iris')!.observations.some(o=>o.kind==='shot'));assert.equal(w.npcs.find(n=>n.id==='ada')!.observations.length,0);assert.equal(lineOfSight({x:-22,z:-22},{x:-22,z:-5}),false);const b=w.npcs[0];b.observations=[];b.pos={x:-22,z:-13};fire(w,'mara',w.items[0],'Test',PLACES.target,'test');assert.equal(b.observations.length,0);});
test('a civilian discovers the incident through proximity and sight',()=>{const w=crime();assert.equal(w.incidents[0].discovered,false);advance(w,10);assert.equal(w.incidents[0].discovered,true);});
test('lab location, collection and reference records gate results',()=>{const w=crime();collectScene(w);submitTest(w,'01-C','prints');assert.equal(w.tests.length,0);w.player={...PLACES.lab};submitTest(w,'01-C','prints');assert.equal(w.tests.length,0);records(w);submitTest(w,'01-C','prints');submitTest(w,'W-104','ballistics');assert.equal(w.tests.length,1);assert.equal(w.facts.filter(f=>f.type==='print').length,0);advance(w,29);assert.equal(w.tests[0].done,false);advance(w,2);assert.equal(w.tests[0].done,true);assert.ok(w.facts.some(f=>f.type==='print'&&f.suspect==='ellis'));});
test('arrest requires all explicit evidence, possession and sales alone fail',()=>{const w=crime();recover(w,'burial');w.player={...PLACES.lab};records(w);assert.equal(arrestAssessment(w,'ellis').supported,false);attemptArrest(w,'ellis');assert.equal(w.phase,'detective');assert.equal(w.outcome,null);});
test('scene, weapon match, firearm print and casing scene tie support arrest',()=>{const w=crime();recover(w,'burial');collectScene(w);lab(w);assert.equal(arrestAssessment(w,'ellis').supported,true);assert.equal(arrestAssessment(w,'leon').supported,false);attemptArrest(w,'ellis');assert.equal(w.phase,'closed');assert.equal(w.outcome!.solved,true);});
test('direct witness can support scene tie when casing was pocketed',()=>{const w=crime();collectCasing(w);recover(w,'burial');collectScene(w);lab(w);assert.equal(arrestAssessment(w,'ellis').supported,false);const iris=w.npcs.find(n=>n.id==='iris')!;w.player={...iris.pos};question(w,iris.id);assert.equal(arrestAssessment(w,'ellis').supported,true);});
test('second actor prints and ballistics do not prove first incident guilt',()=>{const w=crime();w.player={...PLACES.dumpster};dispose(w,'dumpster');advance(w,200);w.phase='detective';w.player={...w.items[0].pos};collectItem(w,'W-104');collectScene(w);lab(w);assert.equal(arrestAssessment(w,'ellis').supported,true);assert.equal(arrestAssessment(w,'mara').supported,false);assert.equal(arrestAssessment(w,'leon').supported,false);});
test('duplicate tests, statements and fact copies cannot improve arrest',()=>{const w=crime();recover(w,'burial');w.player={...PLACES.lab};records(w);submitTest(w,'W-104','prints');submitTest(w,'W-104','prints');assert.equal(w.tests.length,1);advance(w,31);const before=arrestAssessment(w,'ellis');w.facts.push(...structuredClone(w.facts),...structuredClone(w.facts));assert.deepEqual(arrestAssessment(w,'ellis'),before);});
test('save and reload preserve object history, tests and their remaining delay',()=>{const w=crime();recover(w,'river');collectScene(w);w.player={...PLACES.lab};records(w);submitTest(w,'W-104','prints');advance(w,9);let raw='';assert.equal(save(w,{setItem:(_,v)=>raw=v}),true);const restored=load({getItem:()=>raw});assert.deepEqual(restored,JSON.parse(JSON.stringify(w)));advance(restored,22);assert.equal(restored.tests[0].done,true);assert.ok(restored.facts.some(f=>f.type==='print'&&f.suspect==='ellis'));});
test('failed storage, corrupt saves and explicit reset are safe',()=>{const w=crime();assert.equal(save(w,{setItem:()=>{throw new Error('quota');}}),false);assert.equal(load({getItem:()=>'{bad'}).crimeDone,false);assert.equal(createWorld().items.length,1);assert.deepEqual(createWorld().facts,[]);});
test('unsolved ending explains missing requirements',()=>{const w=crime();w.phase='detective';closeUnsolved(w);assert.equal(w.phase,'closed');assert.equal(w.outcome!.solved,false);assert.equal(w.outcome!.reasons.length,4);});
test('collision substeps prevent walking through buildings and river boundary',()=>{const w=createWorld();w.player={x:-22,z:-6};move(w,0,-1,4);assert.ok(w.player.z>=-7.6);w.player={x:28,z:0};move(w,1,0,3);assert.ok(w.player.x<29);});
test('a washed firearm cannot satisfy a fingerprint-based arrest despite a witnessed crime',()=>{const w=crime();w.player={...PLACES.river};dispose(w,'river');advance(w,46);w.phase='detective';w.player={...PLACES.river};search(w,'river');collectItem(w,'W-104');collectScene(w);lab(w);const iris=w.npcs.find(n=>n.id==='iris')!;w.player={...iris.pos};question(w,iris.id);assert.equal(arrestAssessment(w,'ellis').supported,false);assert.ok(w.facts.some(f=>f.key==='prints:W-104:none'));});
test('held object location follows its carrier while preserving deposits',()=>{const w=crime();const gun=w.items[0];handle(w,gun,'mara',w.npcs[2].pos);advance(w,2);assert.deepEqual(gun.pos,w.npcs[2].pos);assert.deepEqual(gun.prints,['leon','ellis','mara']);});
test('successful outcome cites concrete collected facts and removes stale failure feedback',()=>{const w=crime();recover(w,'burial');collectScene(w);lab(w);attemptArrest(w,'leon');assert.ok(w.notice.includes('declined'));attemptArrest(w,'ellis');assert.equal(w.notice,'');assert.ok(w.outcome!.reasons.some(r=>r.includes('W-104')&&r.includes('BR-47')));assert.ok(w.outcome!.reasons.some(r=>r.includes('01-C')&&r.includes('Ellis Vale')));});
