import {chromium} from '@playwright/test';
import {createWorld,acceptContract,acquire,commitCrime,dispose,PLACES,type World} from '../src/sim.ts';
const browser=await chromium.launch({channel:'chrome'});let ctx:any;let p:any;let errors:string[]=[];
async function fixture(w:World){w.started=true;if(ctx)await ctx.close();ctx=await browser.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true,storageState:{cookies:[],origins:[{origin:'http://localhost:5173',localStorage:[{name:'aftertrace-world-v1',value:JSON.stringify(w)}]}]}});p=await ctx.newPage();p.on('pageerror',(e:Error)=>errors.push(e.message));await p.goto('http://localhost:5173');await p.waitForTimeout(500);}

function crime(){const w=createWorld();w.started=true;w.player={...PLACES.contract};acceptContract(w);w.player={...PLACES.pawn};acquire(w,'legal');w.player={...PLACES.target};commitCrime(w);return w;}
const accepted=createWorld();accepted.player={...PLACES.contract};acceptContract(accepted);accepted.player={...PLACES.stolen};await fixture(accepted);await p.getByRole('button',{name:'Steal pistol'}).tap();await p.locator('[data-panel="inventory"]').tap();if(!(await p.locator('#panelBody').innerText()).includes('W-104'))throw new Error('steal UI failed');
const pocket=crime();await fixture(pocket);await p.getByRole('button',{name:'Collect casing'}).tap();await p.locator('[data-panel="inventory"]').tap();if(!(await p.locator('#panelBody').innerText()).includes('Spent casing'))throw new Error('pocket UI failed');
for(const where of ['river','burial','dumpster'] as const){const w=crime();w.player={...PLACES[where]};dispose(w,where);w.phase='detective';w.incidents[0].discovered=true;if(where==='dumpster'){w.npcs[2].pos={x:20,z:10};w.npcs[2].route=[{x:20,z:10}];}await fixture(w);const label=where==='river'?'Search river shallows':where==='burial'?'Excavate disturbed soil':'Search dumpster';await p.getByRole('button',{name:label}).tap();await p.waitForTimeout(where==='burial'?12600:5600);await p.getByRole('button',{name:'Collect firearm'}).tap();await p.locator('[data-panel="inventory"]').tap();if(!(await p.locator('#panelBody').innerText()).includes('W-104'))throw new Error(where+' search/collection UI failed');console.log('PASS UI search/collect',where);}
const unsolved=crime();unsolved.phase='detective';await fixture(unsolved);await p.locator('[data-panel="case"]').tap();await p.getByRole('button',{name:'Compare suspects & assess arrest'}).tap();await p.locator('summary').tap();await p.getByRole('button',{name:'Confirm unsolved outcome'}).tap();await p.waitForTimeout(250);if(!(await p.locator('#panelTitle').innerText()).includes('unsolved'))throw new Error('unsolved UI failed');if((await p.locator('#panelBody').innerText()).includes('What actually happened'))throw new Error('history exposed before opting in');console.log('PASS alternate UI fixtures: stolen pistol, pocket casing, all searches, unsolved, recap gating',errors);await browser.close();
