import './style.css';
import { City } from './scene';
import { load, save, createWorld, tick, move, dist, PLACES, PEOPLE, objective, clock, acceptContract, acquire, commitCrime, collectCasing, dispose, switchPhase, inspectScene, collectItem, search, question, records, submitTest, arrestAssessment, attemptArrest, closeUnsolved, notify, type World, type Vec, type Disposal } from './sim';
let world=load(); let panel=''; let selected='ellis'; let waypoint:Vec|undefined; let waypointName=''; let city:City; let lastTouchAction=-1000; let lastPhase=world.phase; let lastActionHTML=''; let lastPanelHTML=''; let showRecap=false; let storageOK=true;let busy:{label:string;start:number;duration:number;origin:Vec;done:()=>void}|null=null;
const icons={ bag:'<path d="M6 7h12v13H6zM9 7V4h6v3M9 11h6"/>',notes:'<path d="M5 3h14v18H5zM8 8h8M8 12h8M8 16h5"/>',map:'<path d="m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3zM9 3v15M15 6v15"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9.5 9a2.5 2.5 0 1 1 4 2c-1.5.8-1.5 1-1.5 3M12 17h.01"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',arrow:'<path d="m9 5 7 7-7 7"/>',finger:'<path d="M6 17c0-6 0-11 6-11s6 5 6 8M3 12c0-6 3-9 9-9s9 4 9 9M9 20v-7c0-4 6-4 6 0v8M12 13v9"/>',sound:'<path d="M4 9h4l5-4v14l-5-4H4zM17 8a6 6 0 0 1 0 8"/>',reset:'<path d="M4 10a8 8 0 1 1 1 8M4 4v6h6"/>'};
function icon(name:keyof typeof icons){return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+icons[name]+'</svg>';}
const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML=`<main id="game"><canvas id="world" aria-label="Navigable isometric district"></canvas><div class="vignette"></div>
<header class="hud"><div class="wordmark">AFTERTRACE<span class="brand-line">THE CITY REMEMBERS</span></div><div class="phase"><span id="phaseDot"></span><span id="phaseName"></span><time id="clock"></time></div></header>
<section class="objective" aria-label="Current objective"><span id="objectiveTitle">The contract</span><p id="objective"></p><div id="waypoint"></div></section>
<button id="mapButton" class="minimap" aria-label="Open district map"><canvas id="minimap" width="184" height="156"></canvas><span>MERCER DISTRICT ${icon('arrow')}</span></button>
<nav class="tools" aria-label="Game tools"><button data-panel="inventory" title="Inventory · I">${icon('bag')}<span>Inventory</span><b id="itemCount">0</b></button><button data-panel="case" title="Case notes · F">${icon('notes')}<span>Case notes</span><b id="factCount">0</b></button><button data-panel="help" aria-label="Controls and help">${icon('help')}</button></nav>
<div id="worldLabel"></div><div id="toast" role="status" aria-live="polite"></div>
<div class="movement"><div id="joystick" role="application" aria-label="Movement joystick"><div class="joystick-lines"></div><div id="stick"></div></div><span>WASD / ARROWS</span></div>
<section id="interaction" aria-label="Nearby actions"><div id="nearby"></div><div id="actions"></div></section>
<div id="progress" hidden><span></span><div><i></i></div></div>
<footer class="status"><span id="saveStatus">Saved on this device</span><span id="demoNote">ONE WORLD · TWO PERSPECTIVES</span></footer>
<aside id="drawer" hidden><div class="drawer-head"><h1 id="panelTitle"></h1><button id="closePanel" aria-label="Close panel">${icon('close')}</button></div><div id="panelBody"></div></aside>
<section id="welcome" ${world.started?'hidden':''}><div class="welcome-inner"><div class="welcome-rule"></div><h1>Nothing disappears.<br>It waits to be found.</h1><p>One district. A crime. The evidence you leave behind.</p><div class="welcome-phases"><span><b>1</b> Leave a trace</span><span><b>2</b> Build a case</span></div><p class="explain">Play a criminal, then a detective in the <strong>same saved world</strong>. You will know what happened. Your detective must still prove it.</p><button id="begin" class="primary">Enter Mercer District ${icon('arrow')}</button><small>Non-graphic fictional crime · Landscape recommended<br>Headphones optional · Saved automatically</small></div></section>
<div id="confirm" hidden><div><h2>Start a new world?</h2><p>This replaces the saved district, evidence and pending tests on this browser.</p><button id="doReset" class="primary">Start new game</button><button id="cancelReset">Keep this world</button></div></div>
</main>`;
const $=<T extends HTMLElement=HTMLElement>(s:string)=>document.querySelector<T>(s)!;
try {city=new City($('#world'),$('#minimap'));}catch(e){$('#welcome').hidden=false;$('#welcome .welcome-inner').innerHTML='<h1>WebGL could not start.</h1><p>Enable hardware acceleration or open this game in a browser with WebGL support, then reload.</p><button onclick="location.reload()">Try again</button>';throw e;}
function sound(freq=420,duration=.09){if(!audioEnabled)return;try{audio??=new AudioContext();void audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}catch{}}
let audio:AudioContext|undefined;let audioEnabled=false;
function persist(){storageOK=save(world);$('#saveStatus').textContent=storageOK?'Saved on this device':'Save unavailable — allow browser storage';}
function openPanel(name:string){panel=panel===name?'':name;$('#drawer').hidden=!panel;lastPanelHTML='';renderPanel();}
function closePanel(){panel='';$('#drawer').hidden=true;}
$('#begin').onclick=()=>{world.started=true;$('#welcome').hidden=true;notify(world,'Move with the left joystick or WASD. Walk to the payphone, then use the action on the right.');persist();};
document.querySelectorAll<HTMLButtonElement>('[data-panel]').forEach(b=>b.onclick=()=>openPanel(b.dataset.panel!));
$('#mapButton').onclick=()=>openPanel('map');$('#closePanel').onclick=closePanel;
$('#cancelReset').onclick=()=>$('#confirm').hidden=true;
$('#doReset').onclick=()=>{world=createWorld();world.started=true;waypoint=undefined;showRecap=false;busy=null;keys.clear();joy={x:0,y:0};closePanel();$('#confirm').hidden=true;city.victim.rotation.z=0;city.victim.position.y=.35;city.victim.getObjectByName('ring')!.visible=true;for(const mesh of city.itemMeshes.values())mesh.visible=false;persist();notify(world,'New world started. Answer the payphone.');};
function requestReset(){$('#confirm').hidden=false;}
function doAction(fn:()=>void){fn();sound();persist();lastPanelHTML='';renderHUD();renderPanel();}
function timed(label:string,duration:number,fn:()=>void){if(busy)return;busy={label,start:world.playSeconds,duration,origin:{...world.player},done:fn};notify(world,label+'… Stay within reach.');}
const keys=new Set<string>();let joy={x:0,y:0};let joyPointer:number|null=null;let joyCenter={x:0,y:0};
window.addEventListener('keydown',e=>{if(e.target instanceof HTMLSelectElement)return;const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();keys.add(k);if(e.repeat)return;if(k==='escape'){closePanel();$('#confirm').hidden=true;}if(k==='i')openPanel('inventory');if(k==='f')openPanel('case');if(k==='m')openPanel('map');if((k==='e'||k===' ')&&!panel&&$('#welcome').hidden){const b=$<HTMLButtonElement>('#actions button');b?.click();}});
window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();resetJoy();});document.addEventListener('visibilitychange',()=>{keys.clear();resetJoy();persist();});
function resetJoy(){joy={x:0,y:0};joyPointer=null;$('#stick').style.transform='translate(0px,0px)';}
$('#joystick').addEventListener('pointerdown',e=>{if(joyPointer!==null)return;joyPointer=e.pointerId;const r=$('#joystick').getBoundingClientRect();joyCenter={x:r.x+r.width/2,y:r.y+r.height/2};$('#joystick').setPointerCapture(e.pointerId);updateJoy(e);e.preventDefault();});
function updateJoy(e:PointerEvent){if(e.pointerId!==joyPointer)return;const dx=e.clientX-joyCenter.x,dy=e.clientY-joyCenter.y,len=Math.hypot(dx,dy),radius=38;joy={x:dx/Math.max(radius,len),y:dy/Math.max(radius,len)};$('#stick').style.transform=`translate(${joy.x*radius}px,${joy.y*radius}px)`;}
$('#joystick').addEventListener('pointermove',updateJoy);$('#joystick').addEventListener('pointerup',e=>{if(e.pointerId===joyPointer)resetJoy();});$('#joystick').addEventListener('pointercancel',resetJoy);$('#joystick').addEventListener('lostpointercapture',resetJoy);
function defaultGoal():{pos:Vec;name:string}|undefined{
 if(waypoint)return{pos:waypoint,name:waypointName};
 if(world.phase==='criminal'){
 if(!world.accepted)return{pos:PLACES.contract,name:'Payphone'};if(!world.purchase)return{pos:PLACES.pawn,name:'Mercer Pawn'};if(!world.crimeDone)return{pos:PLACES.target,name:'Rowan Pike'};if(!world.disposed)return;return{pos:PLACES.exit,name:'Departure'};
 }if(world.phase==='detective'){if(!world.incidents[0]?.inspected)return{pos:PLACES.target,name:'Scene 01'};if(world.items.some(i=>i.kind==='pistol'&&i.collected))return{pos:PLACES.lab,name:'Forensics'};}return;
}
type Action={id:string;label:string;detail?:string;run:()=>void};let actions:Action[]=[];
$('#actions').addEventListener('pointerup',e=>{if(e.pointerType!=='touch')return;const button=(e.target as HTMLElement).closest<HTMLButtonElement>('button[data-action]');if(!button||button.disabled)return;e.preventDefault();lastTouchAction=performance.now();const a=actions.find(a=>a.id===button.dataset.action);if(a)doAction(a.run);});
function nearbyActions():{place:string;actions:Action[]}{const w=world,p=w.player,out:Action[]=[];let place='Explore Mercer District';const near=(v:Vec,r=3.4)=>dist(p,v)<r;
 if(w.phase==='closed')return{place:'Case closed',actions:[{id:'outcome',label:'Review case outcome',run:()=>openPanel('outcome')}]};
 if(w.phase==='criminal'){
 if(!w.accepted&&near(PLACES.contract)){place='Mercer payphone';out.push({id:'contract',label:'Accept contract',detail:'E',run:()=>acceptContract(w)});}
 if(w.accepted&&!w.purchase){if(near(PLACES.pawn)){place='Mercer Pawn · licensed sale';out.push({id:'buy',label:'Buy pistol',detail:'Recorded purchase',run:()=>acquire(w,'legal')});}if(near(PLACES.stolen)){place='Rear stock crate';out.push({id:'steal',label:'Steal pistol',detail:'No sale record',run:()=>acquire(w,'stolen')});}}
 if(w.purchase&&!w.crimeDone&&near(PLACES.target,3.2)){place='Rowan Pike · alley';out.push({id:'act',label:'Carry out contract',detail:'Non-graphic',run:()=>{commitCrime(w);sound(100,.25);}});}
 const casing=w.items.find(i=>i.kind==='casing'&&i.incident==='01'&&!i.holder&&near(i.pos,3.8));if(casing){place='Spent casing';out.push({id:'pocket',label:'Collect casing',detail:'Or leave it behind',run:()=>collectCasing(w)});}
 if(w.crimeDone&&!w.disposed)for(const where of ['dumpster','river','burial'] as Disposal[])if(near(PLACES[where])){place=where==='dumpster'?'Alley dumpster':where==='river'?'River access':'Wooded clearing';out.push({id:'dispose-'+where,label:where==='burial'?'Bury weapon':where==='river'?'Drop into river':'Discard in dumpster',detail:where==='river'?'Prints wash away over time':'Traces remain',run:()=>timed('Disposing of weapon',where==='burial'?6:2,()=>dispose(w,where))});}
 if(w.disposed&&near(PLACES.exit)){place='Mercer departure';out.push({id:'switch',label:'Become the detective',detail:w.incidents[0]?.discovered?'Same saved world':'Waiting for civilian discovery',run:()=>{switchPhase(w);waypoint=undefined;}});}
 }else{
 for(const incident of w.incidents)if(incident.discovered&&near(incident.pos,4)&&!incident.inspected){place='Reported scene '+incident.id;out.push({id:'inspect-'+incident.id,label:'Document scene '+incident.id,detail:'Collect projectile',run:()=>timed('Documenting scene',4,()=>inspectScene(w,incident.id))});}
 for(const item of w.items)if(item.visible&&!item.holder&&!item.collected&&near(item.pos,4)){place='Evidence within reach';out.push({id:'collect-'+item.id,label:'Collect '+(item.kind==='pistol'?'firearm':item.kind),detail:item.id,run:()=>collectItem(w,item.id)});}
 for(const where of ['dumpster','river','burial'] as Disposal[])if(near(PLACES[where],4)){place=where==='burial'?'Disturbed soil':where==='river'?'River access':'Alley dumpster';out.push({id:'search-'+where,label:where==='burial'?'Excavate disturbed soil':where==='river'?'Search river shallows':'Search dumpster',detail:where==='burial'?'Careful search · 12 seconds':'Search · 5 seconds',run:()=>timed('Searching '+where,where==='burial'?12:5,()=>search(w,where))});}
 if(near(PLACES.lab,4)){place='Forensics · exterior intake';out.push({id:'lab',label:'Submit lab tests',run:()=>openPanel('lab')});out.push({id:'records',label:'Look up records',run:()=>records(w)});}
 else if(near(PLACES.pawn,4)){place='Mercer Pawn';out.push({id:'ledger',label:'Ask for purchase records',run:()=>records(w)});}
 const witnesses=w.npcs.filter(n=>near(n.pos,4.5)).sort((a,b)=>dist(p,a.pos)-dist(p,b.pos));for(const n of witnesses.slice(0,2))out.push({id:'talk-'+n.id,label:'Talk to '+n.name,detail:'Record statement',run:()=>{question(w,n.id);openPanel('case');}});
 }
 return{place,actions:out.slice(0,3)};}
function renderHUD(){const w=world;$('#phaseName').textContent=w.phase==='criminal'?'Ellis Vale · Criminal':w.phase==='detective'?'June Calder · Detective':'Case concluded';$('#phaseDot').className=w.phase;$('#clock').textContent=clock(w.time);$('#objective').textContent=objective(w);$('#objectiveTitle').textContent=w.phase==='criminal'?'The contract':w.phase==='detective'?'The investigation':'The consequences';$('#itemCount').textContent=String(w.items.filter(i=>i.holder===(w.phase==='criminal'?'ellis':'detective')).length);$('#factCount').textContent=String(w.facts.length);
 const goal=defaultGoal();$('#waypoint').textContent=goal?goal.name+' · '+Math.round(dist(w.player,goal.pos))+' m'+(waypoint?' · Map to change':''):(!w.disposed&&w.crimeDone?'Open the map to choose a disposal site.':'');
 const near=nearbyActions();actions=near.actions;$('#nearby').textContent=near.place;const html=actions.length?actions.map(a=>`<button data-action="${a.id}" ${busy?'disabled':''}><span>${a.label}</span>${a.detail?'<small>'+a.detail+'</small>':''}${icon('arrow')}</button>`).join(''):'<div class="no-action">Move closer to interact<span>Use the map to find a destination</span></div>';
 if(html!==lastActionHTML){$('#actions').innerHTML=html;lastActionHTML=html;$('#actions').querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.onclick=()=>{const a=actions.find(a=>a.id===b.dataset.action);if(a&&performance.now()-lastTouchAction>500)doAction(a.run);});}
 $('#toast').textContent=w.notice;$('#toast').classList.toggle('visible',w.time<w.noticeUntil&&!!w.notice);
 $('#progress').hidden=!busy;if(busy){$('#progress span').textContent=busy.label;$('#progress i').style.width=Math.min(100,(w.playSeconds-busy.start)/busy.duration*100)+'%';}
 const label=$('#worldLabel');if(goal&&dist(w.player,goal.pos)<13&&!panel){const p=city.project(goal.pos);label.textContent=goal.name;label.style.left=p.x+'px';label.style.top=p.y+'px';label.hidden=p.x<100||p.x>innerWidth-100||p.y<170||p.y>innerHeight-140;}else label.hidden=true;
 if(w.phase==='closed'&&lastPhase!=='closed'){panel='outcome';$('#drawer').hidden=false;renderPanel();}lastPhase=w.phase;
}
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
function itemRows(lab=false){const items=world.items.filter(i=>i.holder===(world.phase==='criminal'?'ellis':'detective'));return items.length?items.map(i=>`<article class="evidence-row"><div class="item-icon">${icon(i.kind==='pistol'?'bag':'finger')}</div><div><h3>${escape(i.label)}</h3><p>${world.phase==='criminal'?'Carried · details unknown without examination':'Sealed evidence · '+(i.incident?'scene '+i.incident:'recovered in district')}</p>${lab?(['prints','ballistics'] as const).map(kind=>{const t=world.tests.find(t=>t.item===i.id&&t.kind===kind);return `<button class="test-button" data-test="${i.id}:${kind}" ${t?'disabled':''}>${kind==='prints'?'Fingerprint comparison':'Ballistic analysis'} <span>${t?t.done?'Returned':Math.max(0,Math.ceil((t.due-world.time)/world.settings.timeScale))+'s remaining':'Submit · 30s'}</span></button>`;}).join(''):''}</div></article>`).join(''):'<p class="empty">'+(world.phase==='criminal'?'Nothing carried. Accept the contract, then obtain the pistol.':'No evidence collected yet. Document a scene or collect a marked object in the district.')+'</p>';}
function renderPanel(){if(!panel)return;let title='',html='';const w=world;
 if(panel==='inventory'){title='Inventory';html='<p class="intro">'+(w.phase==='criminal'?'Objects keep their identity when they change hands.':'Sealed items preserve earlier traces. Lab tests reveal what can be established.')+'</p>'+itemRows()+(w.phase==='detective'?'<button data-go="lab" class="primary">Find Forensics on the map</button>':'');}
 if(panel==='lab'){title='Forensics intake';html='<p class="intro">Submit at the lab entrance. Tests take 30 seconds of active play; you can leave while they run. Fingerprints require reference records.</p><button id="labRecords">Retrieve reference records</button>'+itemRows(true);}
 if(panel==='case'){
 title='Case 01 · Rowan Pike';if(w.phase==='criminal')html='<p class="intro">The detective’s case opens after the criminal phase. Your hidden actions will not appear here.</p>';else{
 const ballistic=w.facts.filter(f=>f.type==='ballistic'&&f.incident);const linked=ballistic.some(f=>ballistic.some(g=>g.incident!==f.incident&&g.signature===f.signature));
 html='<p class="intro">Collected facts only. Handling, ownership and incident identity are different questions.</p>'+(linked?'<p class="linked">The tested ammunition links scenes 01 and 02 to the same firearm signature. It does not establish the same shooter.</p>':'')+'<div class="case-tabs"><button data-case="facts" class="active">Facts · '+w.facts.length+'</button><button data-case="suspects">Compare suspects</button></div><div id="factsList">'+(w.facts.length?w.facts.map(f=>'<article class="fact"><span>'+f.type+(f.incident?' · SCENE '+f.incident:'')+'</span><p>'+escape(f.text)+'</p></article>').join(''):'<p class="empty">No facts recorded. Walk to the alley and document the scene.</p>')+'</div><button id="compare" class="primary">Compare suspects & assess arrest</button>';
 }}
 if(panel==='suspects'){
 title='Does the evidence support it?';const a=arrestAssessment(w,selected);
 html='<p class="intro">Fictional case rule: all four requirements must be met for incident 01. Purchase or possession alone is insufficient. Duplicate facts count once.</p><label class="select-label" for="suspect">Compare suspect</label><select id="suspect">'+PEOPLE.map(p=>'<option value="'+p.id+'" '+(selected===p.id?'selected':'')+'>'+p.name+' · '+p.role+'</option>').join('')+'</select><div class="requirements">'+a.checks.map(c=>'<p class="'+(c.ok?'met':'missing')+'"><span>'+(c.ok?'Met':'Missing')+'</span>'+c.text+'</p>').join('')+'</div><button id="arrest" class="primary" '+(w.phase==='closed'?'disabled':'')+'>Attempt arrest of '+PEOPLE.find(p=>p.id===selected)!.name+'</button><p class="fine">'+(a.supported?'The collected evidence meets the game’s arrest requirements.':'An unsupported attempt is declined. You can continue investigating.')+'</p><button id="continueCase">'+(w.phase==='closed'?'Return to district':'Continue investigation')+'</button><details class="close-case" '+(w.phase==='closed'?'hidden':'')+'><summary>Close as unsolved</summary><p>This ends the current case without an arrest. The outcome will explain the missing evidence.</p><button id="unsolved">Confirm unsolved outcome</button></details>';
 }
 if(panel==='map'){
 title='Mercer District';html='<p class="intro">Choose a destination. A yellow ring and distance will guide you through the streets.</p><div class="map-legend"><span><i></i> You / destination</span><span>Rose dots · reported scenes</span></div><div class="destinations">';
 const destinations:[string,string,string][]=[['contract','Mercer payphone','Contract'],['pawn','Mercer Pawn','Purchase / records'],['stolen','Rear stock crate','Behind the pawnshop'],['target','Mercer alley','Rowan Pike / scene 01'],['dumpster','Alley dumpster','Traces preserved · possible retrieval'],['river','River access','Water degrades prints over time'],['burial','Wooded clearing','Traces preserved · careful search'],['lab','Forensics','Tests / reference records'],['exit','Mercer departure','Switch perspectives']];if(w.incidents.some(i=>i.id==='02'&&i.discovered))destinations.push(['second','Harbor Walk · scene 02','New civilian report']);
 html+=destinations.map(([key,name,note])=>'<button data-go="'+key+'"><span>'+name+'<small>'+note+'</small></span><b>'+Math.round(dist(w.player,PLACES[key as keyof typeof PLACES]))+' m</b></button>').join('')+'</div><button id="clearWaypoint">Clear destination</button>';
 }
 if(panel==='help'){
 title='How to play';html='<p class="intro">Nothing you do disappears. It waits to be found.</p><h2>Move through the district</h2><p>Left thumb: joystick. Right thumb: contextual actions. Keyboard: WASD or arrows, E to interact. I opens inventory, F case notes, M map. Escape closes a panel.</p><h2>Criminal → Detective</h2><p>Accept the payphone contract. Buy or steal the pistol. Find Rowan in the alley. After the non-graphic act, take or leave the casing and choose a disposal site. Return to departure after a civilian reports the scene.</p><h2>Build a case</h2><p>Document the scene, collect marked evidence, talk to pedestrians, and look up records at the shop or lab. Submit fingerprint and ballistic tests at Forensics. Compare suspects in case notes.</p><h2>The district remembers</h2><p>Dumpsters preserve traces, but a civilian can retrieve and reuse an object. Water removes prints after '+Math.round(w.settings.waterWashSeconds/w.settings.timeScale)+' seconds submerged; ballistics remain. Burial preserves traces but requires a 12-second excavation.</p><p>These are fictional gameplay rules. Prints establish handling without a timestamp. Ballistics link a weapon, not a person. The detective sees only collected observations and test results.</p><h2>Save & timing</h2><p>Auto-saved locally. Reload restores the same world and pending tests. Simulation pauses when the tab is hidden. This first case is designed for an unhurried 10–15 minute exploration; familiar routes can be completed faster.</p><button id="audio">'+icon('sound')+(audioEnabled?'Sound on · mute':'Sound off · enable')+'</button><button id="reset" class="danger">'+icon('reset')+'New game</button>';
 }
 if(panel==='outcome'){
 title=w.outcome?.solved?'An arrest. A supported case.':'The case remains unsolved.';
 html='<p class="intro">'+(w.outcome?.solved?PEOPLE.find(p=>p.id===w.outcome?.suspect)?.name+' was arrested for the alley incident. The case rests on these collected facts:':'The available evidence did not lead to an arrest. The case closed with these gaps:')+'</p><div class="outcome-reasons">'+(w.outcome?.reasons||[]).map(r=>'<p>'+escape(r)+'</p>').join('')+'</div><p class="fine">Played '+Math.floor(w.playSeconds/60)+'m '+Math.floor(w.playSeconds%60)+'s. One continuous saved world. An arrest is the end of this demonstration, not a court verdict.</p><button id="recap" class="primary">'+(showRecap?'Hide full event history':'Reveal full event history')+'</button>'+(showRecap?'<h2>What actually happened</h2><p class="fine">Post-case reveal. This hidden history was unavailable to the detective.</p><ol class="timeline">'+w.events.map(e=>'<li><time>'+clock(e.time)+'</time><div>'+escape(e.action)+'<small>'+escape(e.actor)+(e.from?' · '+escape(e.from)+' → '+escape(e.to||'world'):'')+'</small></div></li>').join('')+'</ol>':'')+'<button id="reset" class="danger">Start a different chain of events</button>';
 }
 $('#panelTitle').textContent=title;if(html===lastPanelHTML)return;const scroll=$('#panelBody').scrollTop;$('#panelBody').innerHTML=html;$('#panelBody').scrollTop=scroll;lastPanelHTML=html;
 const bind=(s:string,fn:()=>void)=>{const e=document.querySelector<HTMLButtonElement>(s);if(e)e.onclick=()=>doAction(fn);};
 bind('#labRecords',()=>records(w));bind('#compare',()=>openPanel('suspects'));bind('[data-case="suspects"]',()=>openPanel('suspects'));bind('[data-case="facts"]',()=>$('#factsList').scrollIntoView({block:'start',behavior:'smooth'}));bind('#arrest',()=>attemptArrest(w,selected));bind('#unsolved',()=>closeUnsolved(w));bind('#continueCase',closePanel);bind('#clearWaypoint',()=>{waypoint=undefined;closePanel();});bind('#reset',requestReset);bind('#audio',()=>{audioEnabled=!audioEnabled;sound();});bind('#recap',()=>{showRecap=!showRecap;lastPanelHTML='';renderPanel();});
 const sel=$<HTMLSelectElement>('#suspect');if(sel)sel.onchange=()=>{selected=sel.value;lastPanelHTML='';renderPanel();};
 document.querySelectorAll<HTMLButtonElement>('[data-go]').forEach(b=>b.onclick=()=>{const key=b.dataset.go as keyof typeof PLACES;waypoint=PLACES[key];waypointName=({contract:'Payphone',pawn:'Mercer Pawn',stolen:'Rear stock crate',target:'Mercer alley',dumpster:'Alley dumpster',river:'River access',burial:'Wooded clearing',lab:'Forensics',exit:'Departure',second:'Scene 02'} as Record<string,string>)[key];closePanel();notify(w,'Destination set: '+waypointName+'. Follow the yellow ring and distance.');});
 document.querySelectorAll<HTMLButtonElement>('[data-test]').forEach(b=>b.onclick=()=>doAction(()=>{const [id,kind]=b.dataset.test!.split(':');submitTest(w,id,kind as 'prints'|'ballistics');}));
}
let last=performance.now(),uiElapsed=0,saveElapsed=0;function frame(now:number){const dt=Math.min(.06,(now-last)/1000);last=now;let moving=false;if(world.started&&!document.hidden&&$('#confirm').hidden){tick(world,dt);if(!panel&&world.phase!=='closed'){
 let sx=joy.x+(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),sy=joy.y+(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);
 const len=Math.hypot(sx,sy);if(len>.1){sx/=Math.max(1,len);sy/=Math.max(1,len);const old={...world.player};move(world,sx*.79+sy*.61,-sx*.61+sy*.79,dt);moving=dist(old,world.player)>.001;}
 }if(busy){if(dist(world.player,busy.origin)>2){busy=null;notify(world,'Action interrupted. Return to the site and try again.');}else if(world.playSeconds-busy.start>=busy.duration){const done=busy.done;busy=null;doAction(done);}}
 }
 city.update(world,dt,moving,defaultGoal()?.pos);uiElapsed+=dt;saveElapsed+=dt;if(uiElapsed>.12){renderHUD();if(panel)renderPanel();uiElapsed=0;}if(saveElapsed>2){persist();saveElapsed=0;}requestAnimationFrame(frame);}
window.addEventListener('pagehide',persist);renderHUD();requestAnimationFrame(frame);
// Read-only diagnostic summary, with no event history or secret traces in the UI.
Object.defineProperty(window,'aftertraceDiagnostics',{get:()=>({phase:world.phase,position:{...world.player},fps:Math.round(city.fps),drawCalls:city.renderer.info.render.calls,triangles:city.renderer.info.render.triangles,facts:world.facts.length,tests:world.tests.map(t=>({id:t.id,done:t.done})),saveOK:storageOK})});
